version: '3'
services:
  redis-server:
    image: redis:7-alpine
    container_name: redis-server
    volumes:
      - ./cluster.sh:/cluster.sh
    command: sh /cluster.sh
    networks:
      redis-net:
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6

  redis-node1:
    image: redis:7-alpine
    container_name: redis-node1
    volumes:
      - ./redis_6300.conf:/etc/redis/redis_6300.conf
    command: redis-server /etc/redis/redis_6300.conf
    networks:
      redis-net:
    ports:
      - 6300:6300
      - 16300:16300


  redis-node2:
    image: redis:7-alpine
    container_name: redis-node2
    volumes:
      - ./redis_6301.conf:/etc/redis/redis_6301.conf
    command: redis-server /etc/redis/redis_6301.conf
    networks:
      redis-net:
    ports:
      - 6301:6301
      - 16301:16301

  redis-node3:
    image: redis:7-alpine
    container_name: redis-node3
    volumes:
      - ./redis_6302.conf:/etc/redis/redis_6302.conf
    command: redis-server /etc/redis/redis_6302.conf
    networks:
      redis-net:
    ports:
      - 6302:6302
      - 16302:16302

  redis-node4:
    image: redis:7-alpine
    container_name: redis-node4
    volumes:
      - ./redis_6400.conf:/etc/redis/redis_6400.conf
    command: redis-server /etc/redis/redis_6400.conf
    networks:
      redis-net:
    ports:
      - 6400:6400
      - 16400:16400


  redis-node5:
    image: redis:7-alpine
    container_name: redis-node5
    volumes:
      - ./redis_6401.conf:/etc/redis/redis_6401.conf
    command: redis-server /etc/redis/redis_6401.conf
    networks:
      redis-net:
    ports:
      - 6401:6401
      - 16401:16401


  redis-node6:
    image: redis:7-alpine
    container_name: redis-node6
    volumes:
      - ./redis_6402.conf:/etc/redis/redis_6402.conf
    command: redis-server /etc/redis/redis_6402.conf
    networks:
      redis-net:
    ports:
      - 6402:6402
      - 16402:16402

networks:
  redis-net:
    driver: bridge
